apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: contrail-system-k8s-apiserver-autoscaler-chaos
  namespace: litmus
spec:
  appinfo:
    appns: 'contrail-system'
    applabel: 'app=contrail-k8s-apiserver'
    appkind: 'deployment'
  annotationCheck: 'true'
  engineState: 'active'
  auxiliaryAppInfo: ''
  chaosServiceAccount: litmus-admin
  jobCleanUpPolicy: 'delete'
  monitoring: false
  experiments:
    - name: pod-autoscaler
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '120'

            - name: REPLICA_COUNT
              value: '3'
